---
- name: Install Epel-release
  dnf:
    name:
      - epel-release
    state: present
  become: true

- name: Enable CRB (PowerTools) repository
  command:
    cmd: dnf config-manager --set-enabled crb
  become: true

- name: Install Nginx
  dnf:
    name:
      - nginx
    state: present
  notify:
    - Enable and start Nginx service
  become: true

- name: Build and install upload module
  import_tasks: build_module.yml
