---
name: CI
"on":
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "usegalaxy_eu.ansible-nginx-upload-module"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible-community/ansible-lint-action@main
